### ISSUE TITLE
The registration topic failed after upgrading from 4.9.0 to 5.0.1, as shown below

### ISSUE THREAD

**Issue by iloveuav** [apache/echarts#14218]
### Version
5.0.1

### Steps to reproduce
```js
import echarts from 'echarts/lib/echarts';
import { ThemeType, ChartType } from '@utils/Enum';
import { IBaseChartConfig } from '@iwtypes/IBaseChartConfig';
import blueTheme from './blue';
import greenTheme from './green';
import darkTheme from './dark';

import greenEChartTheme from './green/green.json';
import blueEChartTheme from './blue/blue.json';
import darkEChartTheme from './dark/dark.json';

// 注册echarts主题
echarts.registerTheme(`${ThemeType.GREEN}theme`, greenEChartTheme);
echarts.registerTheme(`${ThemeType.BLUE}theme`, blueEChartTheme);
echarts.registerTheme(`${ThemeType.DARK}theme`, darkEChartTheme);

export function getChartThemeConfig(
  chart: ChartType,
  theme?: ThemeType
): IBaseChartConfig {
  if (theme === ThemeType.BLUE) {
    return blueTheme[chart];
  } else if (theme === ThemeType.DARK) {
    return darkTheme[chart];
  } else {
    return greenTheme[chart];
  }
}
```
-----------------------------------

©>Uncaught TypeError:index.ts?6a07:13echarts lib echarts WEBPACK IMPORTED MODULE 0 .default.registerTheme is not a function

### What is expected?
Subject normal registration

### What is actually happening?
Failed to register the subject

**Comment by pissang** [comment]
Please use named exports

```js
import * as echarts from 'echarts/lib/echarts';
```

Here is an upgrade guide.

https://echarts.apache.org/zh/tutorial.html#ECharts%205%20%E5%8D%87%E7%BA%A7%E6%8C%87%E5%8D%97

**Comment by iloveuav** [comment]
> Please use named exports
> 
> ```js
> import * as echarts from 'echarts/lib/echarts';
> ```
> 
> Here is an upgrade guide.
> 
> https://echarts.apache.org/zh/tutorial.html#ECharts%205%20%E5%8D%87%E7%BA%A7%E6%8C%87%E5%8D%97

This issue has been resolved according to the upgrade guide, but there are other compatibility issues I will try to resolve first. Thank you for your answer
